### ISSUE TITLE
Get rid of the `flipVertical` command, and implement it as a flag to the `flip` command

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/pixs#5]
It would really make more sense for `flipVertical` to be executed through `flip --vertical` and similarly for `flipHorizontal` as `flip --horizontal`. If no flag is given, the image should be flipped about the origin.

**Comment by MortimerMcMire315** [comment]
[Here](https://github.com/MortimerMcMire315/pixs/commit/2892da22db8396d06e61211b1f1216af4b8ad9ae)'s my attempt at this one. I didn't create a pull request or merge into my master branch because I'm not crazy about how it turned out, but I'm wondering if you could take a look at it and see if there's a better solution.

**Comment by ayberkt** [comment]
@MortimerMcMire315 thanks for that! How does @joom feel about this? I think it's okay to introduce some cyclomatic complexity to prevent commands from working in a counter-intuitive way. But I don't know if this approach will scale. For example, I was trying to add a command for the [`makeHistogram` function](https://github.com/ayberkt/pixs/blob/master/src/Pixs/Information/Histogram.hs#L48) and the only possible way seems to be introducing a new constructor for `CommandType` which will increase repetition when implementing [`run`](https://github.com/ayberkt/pixs/blob/master/app/Main.hs#L173). I'm wondering if we can come up with a generic solution.

**Comment by joom** [comment]
@MortimerMcMire315's solution assumes that there are two possible flips, but I think @ayberkt's idea is to have three: origin, horizontal, and vertical, where origin is the default. Personally, I don't think there has to be a default, we can just require an argument about what direction to flip in.

I think we can do this using `ArgT` if we give up on flags and add a direction argument. You can see it here: 5f63fc3. 

I know that the commands are not very elegant, they will look like this: `pixs flip --in ... -d Horizontal --out ...`, maybe we can add aliases for the flip options, e.g. `Horizontal` can be `horizontal` and `h`. (We would have to define our own `Read` instance for `FlipDirection`)

I don't know, this is just an idea. Also, I thought it was a good use case for `ExistentialQuantification` and `GADTs`. :smiley:

**Comment by MortimerMcMire315** [comment]
This is cool! And a good use of `ExistentialQuantification`/`GADTs`, when paired with @joom's `Read` instance definitions.

**Comment by ayberkt** [comment]
@joom's branch merged!
